CREATE DATABASE IF NOT EXISTS `DKPDB`
USE `DKPDB`;

CREATE TABLE IF NOT EXISTS `DKPTB` (
  `ID` smallint(5) unsigned zerofill NOT NULL AUTO_INCREMENT,
  `name` text,
  `DKP` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;
